spring :
  profiles :
    active : local
---
spring :
  profiles: local
  session :
    timeout: 600
  servlet:
    multipart:
      enabled : true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\IntellijProject\\find-chat\\file
    encoding :
      encoding :
        charset : UTF-8
        force : true

  jackson:
    default-property-inclusion: NON_NULL

  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher
server :
  port : 8000
  session:
    timeout : 600
swagger :
  enable : true

---
spring :
  profiles: server
  session :
    timeout: 600
  servlet:
    multipart:
      enabled : true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\IntellijProject\\find-chat\\file
    encoding :
      encoding :
        charset : UTF-8
        force : true

  jackson:
    default-property-inclusion: NON_NULL

  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher
server :
  port : 8000
  session:
    timeout : 600
swagger :
  enable : true

